# Docker Compose for BSC Support Agent - Local Development
# Docker Compose v2 format (version field is obsolete)

services:
  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # Environment variables loaded from backend/.env file
    env_file:
      - ../../apps/backend/.env
    volumes:
      # Mount for development (comment out for production)
      - ../../apps/backend:/app
      - /app/venv # Exclude venv from mount
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
# For production deployment, create docker-compose.prod.yml with:
# - No volume mounts
# - Production environment variables
# - Resource limits
# - Restart policies